### ISSUE TITLE
Set up Webpack and PostCSS build system for Quick helper chrome extension

### ISSUE THREAD

**Issue by himanshuramavat** [therohanparmar/quick-helper-chrome-ext#13]
### Task:

Set up a build process for the Chrome extension to bundle JavaScript and process CSS for easier maintenance and future development.

### Details:

- [x] 1. Configure **Webpack** to bundle JavaScript from the `src/` folder and output it to the `dist/` folder.
- [x] 2. Use **PostCSS** with **Autoprefixer** to process CSS files and output them to the `dist/` folder.
- [x] 3. Add **npm scripts** for `build` to automate the build process.
- [x] 4. Update `manifest.json` to reference the build output from the `dist/` folder.
- [x] 5. Move existing JavaScript and CSS files from `assets/` to the `src/` folder.
- [x] 6. Ensure `popup.html` references the compiled JS and CSS files from dist/.

### Acceptance Criteria:

Running `npm run build` should generate the production-ready `dist/ `folder with compiled JS and CSS.
All source files remain in `src/`, and the build process outputs to `dist/`.
The Chrome extension should load correctly using files from `dist/`.

### Project Structure

```bash
/quick-helper-chrome-ext
│
├── /assets
│   ├── /js
│   │   └── main.js
│   ├── /css
│   │   └── styles.css
│   └── index.html
│
├── /src
│   ├── /js
│   │   └── main.js
│   ├── /css
│   │   └── styles.css
│   └── index.html
│
├── /dist
│   ├── /js
│   │   └── main.js  # Build JS Output
│   ├── /css
│   │   └── styles.css  # Build CSS Output
│   └── index.html
│
├── webpack.config.js
├── postcss.config.js
├── package.json
└── manifest.json

```

**Comment by himanshuramavat** [comment]
@therohanparmar 
 
Below is the sccss structure for now, we can change it according to our requirements.
```
scss/
│
├── _variables.scss     // Contains color variables, fonts, etc.
├── _global.scss        // Global styles like reset, box-sizing, and body.
├── _layout.scss        // Layout styles like `.main`.
├── _components.scss    // Component-specific styles like `.value-wrap`, `.section-key`, etc.
├── _dark-mode.scss     // Dark mode styles.
└── styles.scss         // Main SCSS file that imports everything.
```

**Comment by himanshuramavat** [comment]
Hey @therohanparmar 

Please review the folder structure and let me know if anything needs to be changed!

Thanks
